"use strict";
exports.__esModule = true;
var express_1 = require("express");
var categoryController = require("../controllers/category");
var router = (0, express_1.Router)();
router.route('/').get(categoryController.getCategories);
router.route('/:id').get(categoryController.getCategoryById);
router.route('/').post(categoryController.createCategory);
router.route('/:id').patch(categoryController.updateCategory);
router.route('/:id')["delete"](categoryController.deleteCategory);
exports["default"] = router;
