"use strict";
exports.__esModule = true;
var express_1 = require("express");
var manufacturerController = require("../controllers/manufacturer");
var router = (0, express_1.Router)();
router.route('/').get(manufacturerController.getManufacturers);
router.route('/:id').get(manufacturerController.getManufacturerById);
router.route('/').post(manufacturerController.createManufacturer);
router.route('/:id').patch(manufacturerController.updateManufacturer);
router.route('/:id')["delete"](manufacturerController.deleteManufacturer);
exports["default"] = router;
