"use strict";
exports.__esModule = true;
var express_1 = require("express");
var productController = require("../controllers/product");
var router = (0, express_1.Router)();
router.route('/').get(productController.getProducts);
router.route('/:id').get(productController.getProductById);
router.route('/').post(productController.createProduct);
router.route('/:id').patch(productController.updateProduct);
router.route('/:id')["delete"](productController.deleteProduct);
exports["default"] = router;
