"use strict";
exports.__esModule = true;
var express_1 = require("express");
var productResourceController = require("../controllers/productResource");
var router = (0, express_1.Router)();
router.route('/').get(productResourceController.getProductResources);
router.route('/:id').get(productResourceController.getProductResourceById);
router.route('/').post(productResourceController.createProductResource);
router.route('/:id').patch(productResourceController.updateProductResource);
router.route('/:id')["delete"](productResourceController.deleteProductResource);
exports["default"] = router;
