-- CreateTable
CREATE TABLE `StaticPageData` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `data` VARCHAR(191) NOT NULL,
    `type` ENUM('ABOUT', 'CONTACT_US', 'SERVICE', 'BANNER') NOT NULL,
    `subType` ENUM('HEAD_QUARTER', 'GET_IN_TOUCH_1', 'GET_IN_TOUCH_2', 'MAP', 'BODY', 'SOCIAL') NOT NULL,
    `dataType` ENUM('HTML_TEXT', 'TWITTER', 'FACEBOOK', 'INSTAGRAM', 'YOUTUBE', 'NAME', 'ADDRESS', 'EMAIL', 'PHONE', 'LINK', 'OTHER') NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `StaticPageData_id_key`(`id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
